AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 25
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ClassLength:
  Max: 250

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - 'lib/s3arch/searcher.rb'
